/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'topic' : IDL.Text,
  'answers' : IDL.Vec(IDL.Text),
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
});
export const Result = IDL.Record({
  'topic' : IDL.Text,
  'total' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'percentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestionByText' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
  'getResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
  'submitResult' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'answers' : IDL.Vec(IDL.Text),
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
  });
  const Result = IDL.Record({
    'topic' : IDL.Text,
    'total' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'percentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestionByText' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getResults' : IDL.Func([], [IDL.Vec(Result)], ['query']),
    'submitResult' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Float64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };