/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Question = IDL.Record({
  'topic' : IDL.Text,
  'answers' : IDL.Vec(IDL.Text),
  'explanation' : IDL.Text,
  'text' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
  'getQuestionByText' : IDL.Func([IDL.Text], [Question], ['query']),
  'getQuestionsByTopic' : IDL.Func([IDL.Text], [IDL.Vec(Question)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Question = IDL.Record({
    'topic' : IDL.Text,
    'answers' : IDL.Vec(IDL.Text),
    'explanation' : IDL.Text,
    'text' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getQuestion' : IDL.Func([IDL.Nat], [Question], ['query']),
    'getQuestionByText' : IDL.Func([IDL.Text], [Question], ['query']),
    'getQuestionsByTopic' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Question)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };